/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const RaceIndexLazyImport = createFileRoute('/race/$index')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const RaceIndexLazyRoute = RaceIndexLazyImport.update({
  path: '/race/$index',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/race.$index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/race/$index': {
      id: '/race/$index'
      path: '/race/$index'
      fullPath: '/race/$index'
      preLoaderRoute: typeof RaceIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  RaceIndexLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/race/$index"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/race/$index": {
      "filePath": "race.$index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
